---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 2
        args:
        - name: service-name
          value: recommendation.default.svc.cluster.local
      steps:
      - setWeight: 20
      - pause:
          duration: "20s"
      - setWeight: 50
      - pause:
          duration: "20s"
      canaryService: recommendation-canary
      stableService: recommendation-stable
      trafficRouting:
        istio:
          virtualService: 
            name: recommendation-vsvc
            routes:
            - primary # At least one route is required
          destinationRule:
            name: recommendation-destrule
            canarySubsetName: canary
            stableSubsetName: stable
          
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: recommendation
      version: v1
  template:
    metadata:
      labels:
        app: recommendation
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xms15m -Xmx15m -Xmn15m
        name: recommendation
        image: quay.io/rhdevelopers/istio-tutorial-recommendation:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health          
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health          
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: recommendation
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: recommendation-canary
#spec:
#  ports:
#  - name: http
#    port: 8080
#  selector:
#    app: recommendation
#---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    successCondition: result[0] >= 0.95
    interval: 30s
    failureLimit: 1
    provider:
      prometheus:
        address: http://prometheus.istio-system.svc.cluster.local:9090
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[1m]
          )) / 
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[1m]
          ))
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: recommendation-destrule
spec:
  host: recommendation
  subsets:
  - name: canary   # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
    labels:        # labels will be injected with canary rollouts-pod-template-hash value
      app: recommendation
  - name: stable   # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
    labels:        # labels will be injected with canary rollouts-pod-template-hash value
      app: recommendation